[general]
import = ["~/.config/alacritty/themes/rose-pine-dawn.toml"]
live_config_reload = true

[cursor.style]
blinking = "Never"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 1.0

[window.padding]
x = 8
y = 8
